### ISSUE TITLE
The code to transform SoNar to Conll format neglected important information

### ISSUE THREAD

**Issue by SysDevHayes** [andreasvc/dutchcoref#2]
Hi Andrea,

Thank you so much for this interesting work. I'm working on training the neuralcoref model on the Dutch language using the SoNar corpus. According to their tutorial, I have to transform the SoNar corpus to Conll. This is the expected file format.

![image](https://user-images.githubusercontent.com/46409458/83350651-c2993180-a367-11ea-884e-1bb9796cc020.png)

However, after using your script, I get this:
![image](https://user-images.githubusercontent.com/46409458/83350683-f70ced80-a367-11ea-843e-d33bf3326737.png)

My question is, is this a normal behavior? (as I saw it a bit different from the example you shown on this repo). Also, how can I use the code from this repo to let's say, predict Coref given a couple of Dutch sentences?

Thank you!

**Comment by andreasvc** [comment]
The conversion script focuses on the task of producing the column with the coreference chains. This last column, together with the tokens, is the only information needed by an end-to-end model. Other kinds of models do rely on parse features.

If you need the other information, you could extract parts of it from SoNaR data, although that has no speaker information AFAIK. Another possibility is to run a parser (Alpino or spaCy). The addparsebits.py script can be used to add such information to the CoNLL file. However, IIRC, neuralcoref uses spaCy to parse sentences and does not read the parses from the CoNLL file.

> Also, how can I use the code from this repo to let's say, predict Coref given a couple of Dutch sentences?

The example in the README contains instructions for that. You first run the Alpino parser and then pass its output to coref.py.

**Comment by EricLe-dev** [comment]
@andreasvc thank you so much for your detailed answer.
I tried to follow the README but did not work. When I do:
`go get ./...`
I gave me this error:
![image](https://user-images.githubusercontent.com/46409458/83402344-c80e7e80-a430-11ea-96ce-e7509b173772.png)

I checked the Environmental Variables (I'm using Windows 10) but all the variables related to Go were setup properply. I guess maybe Windows was the problem.

My questions are:
1. Is that possible to run the Alpino parser on Windows machine? If so, can you please give me a small guidance on this as I'm quite new to Go?
2. Is that possible to replace the Alpino parser by other parser (I'm more familiar to spaCy)? If it's possible, can you please give me some [example output of this code](https://github.com/andreasvc/dutchcoref/blob/master/web.py#L73) so I can reconstruct the output of the spaCy parser accordingly to satisfy the coref function?

Thank you so much!
