### ISSUE TITLE
The possibility to replace Alpino parser by spaCy parser

### ISSUE THREAD

**Issue by SysDevHayes** [andreasvc/dutchcoref#3]
Hi @andreasvc thank you so much for your detailed answer for the previous issue.
I tried to follow the README but did not work. At the step to start the [Alpino server](https://github.com/andreasvc/alpino-api/tree/master/demo), when I do:
`go get ./...`
I gave me this error:
![image](https://user-images.githubusercontent.com/46409458/83402344-c80e7e80-a430-11ea-96ce-e7509b173772.png)

I checked the Environmental Variables (I'm using Windows 10) but all the variables related to Go were setup properply. I guess maybe Windows was the problem.

My questions are:
1. Is that possible to run the Alpino parser on Windows machine? If so, can you please give me a small guidance on this as I'm quite new to Go?
2. Is that possible to replace the Alpino parser by other parser (I'm more familiar to spaCy)? If it's possible, can you please give me some [example output of this code](https://github.com/andreasvc/dutchcoref/blob/master/web.py#L73) so I can reconstruct the output of the spaCy parser accordingly to satisfy the coref function?

Thank you so much!

**Comment by andreasvc** [comment]
1. I don't know about Windows, but I would advise to run Linux via [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). There's no need to run Go, that's only for the web demo, not needed for the example in the README.
2. Not really, that would be a rewrite.
