### ISSUE TITLE
Achieving the same result as the knack_file7.dutchcoref.conll file

### ISSUE THREAD

**Issue by ambernorder** [andreasvc/dutchcoref#4]
Hello,

I'm working on my master thesis and I'm very interested in your coreference system.
I believe I have everything working now, but I'm not able to achieve the same results with the semeval2010 file_7 when I compare it to the knack_file7.dutchcoref.conll file, as mentioned in the paper. 

I used the parsed .XML files in the semeval2010NLdevparses/file_7 folder and after that used the recommended scorer to look at the results. 

first:
python3 .\coref.py --fmt=conll2012 .\data\semeval2010NLdevparses\file_7\ > file_7.conll
and then: 
python3 .\evaluation\scorer.py .\data\manualeval\knack_file7.gold.conll .\file_7.conll

I'm only able to achieve a CoNLL score of 55.06. 

I there something I'm missing? 

Thank you in advance!

**Comment by andreasvc** [comment]
Good question. This is not properly documented I guess.

You have to enable the right settings for the SemEval annotation scheme. With the `--semeval` option this is done automatically (see the `semeval()` function). If you run on a single file as in your example, you need to specify the post-processing options explicitly:

```bash
$ python3 coref.py --fmt=semeval2010 --exclude=relpronouns,reflexives,reciprocals,predicatives,appositives,npsingletons,relpronounsplit data/semeval2010NLdevparses/file_7 >/tmp/file_7.conll
$ python3 ~/code/coval/scorer.py data/manualeval/knack_file7.gold.conll /tmp/file_7.conll
             recall  precision         F1
mentions      75.00      78.95      76.92
muc           70.00      70.00      70.00
bcub          65.00      72.81      68.68
ceafe         70.09      77.88      73.78
ceafm         75.00      78.95      76.92
lea           60.00      68.42      63.93
CoNLL score:  70.82
```

This is with current master, and this score is slightly lower than the one in the paper. Some of the improvements that I have made after the paper was published are apparently regressions for this particular document. Let's reproduce the score from the paper:

```bash
$ git checkout 5b33ab4e2f4bc29619d3f3fdbef462ccd4807aef
[...]
$ python3 coref.py --fmt=semeval2010 --exclude=relpronouns,reflexives,reciprocals,predicatives,appositives,npsingletons,relpronounsplit data/semeval2010NLdevparses/file_7 >/tmp/file_7.conll
Traceback (most recent call last):
[...]
ValueError: unrecognized --exclude argument: reflexives
$ python3 coref.py --fmt=semeval2010 --exclude=relpronouns,reflectives,reciprocals,predicatives,appositives,npsingletons data/semeval2010NLdevparses/file_7 >/tmp/file_7.conll
$ python3 ~/code/coval/scorer.py data/manualeval/knack_file7.gold.conll /tmp/file_7.conll
             recall  precision         F1
mentions      70.00      87.50      77.78
muc           70.00      77.78      73.68
bcub          60.00      80.21      68.65
ceafe         60.09      85.84      70.70
ceafm         70.00      87.50      77.78
lea           55.00      75.00      63.46
CoNLL score:  71.01
```

Notice how the post processing options are slightly different, but the score is reproduced exactly. Let me know if you run into anything else!
